version: "3.8"

services:

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    restart: always
    environment:
      POSTGRES_DB: stats
      POSTGRES_USER: stats_user
      POSTGRES_PASSWORD: stats_pass
    ports:
      - "5433:5432"
    volumes:
      - stats_data:/var/lib/postgresql/data
    networks:
      - ewm-net

  stats-server:
    build:
      context: ./stats/stats-server
    container_name: stats-server
    depends_on:
      - stats-db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://stats-db:5432/stats
      SPRING_DATASOURCE_USERNAME: stats_user
      SPRING_DATASOURCE_PASSWORD: stats_pass
    ports:
      - "9090:9090"
    networks:
      - ewm-net

  main-db:
    image: postgres:16.1
    container_name: main-db
    restart: always
    environment:
      POSTGRES_DB: ewm
      POSTGRES_USER: ewm_user
      POSTGRES_PASSWORD: ewm_pass
    ports:
      - "5434:5432"
    networks:
      - ewm-net

  ewm-service:
    build:
      context: ./main-service
    container_name: ewm-service
    depends_on:
      - main-db
      - stats-server
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://main-db:5432/ewm
      SPRING_DATASOURCE_USERNAME: ewm_user
      SPRING_DATASOURCE_PASSWORD: ewm_pass
      STATS_SERVER_URL: http://stats-server:9090
    ports:
      - "8080:8080"
    networks:
      - ewm-net

networks:
  ewm-net:

volumes:
  stats_data: